spring.application.name=parcial02

spring.jpa.hibernate.ddl-autp=update

spring.datasource.url=jdbc:postgresql://localhost:5432/magic_wand
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.show-sql=true

spring.datasource.username=postgres
spring.datasource.password=analissa
spring.datasource.driver-class-name=org.postgresql.Driver
